### ISSUE TITLE
Eslint rules configuration

### ISSUE THREAD

**Issue by ghost** [bixlabs/documentation#2]
The `.eslintrc` rules are configured incorrectly, right now it is defined like this:

```
{
  "extends": "airbnb",
  "comma-dangle": ["error", "never"],
}
```

It should be:

```
{
  "extends": "airbnb",
  "rules": {
    "comma-dangle": ["error", "never"]
  }
}
```

Otherwise the rules configuration will be ignored.

Also, I don't know about that trailing comma, should we keep it? What do you think? :)

**Comment by jac1013** [comment]
Hi @evasquez26 You are right, if possible create a PR to apply the changes.

Thanks!
