### ISSUE TITLE
Improvements for the Pull Request Template

### ISSUE THREAD

**Issue by jac1013** [bixlabs/documentation#4]
Hello Guys,

So this is the [Template](https://github.com/bixlabs/documentation/blob/master/PULL_REQUEST_TEMPLATE.md), I would like to point out some improvements and let me know what you think:

1. I think the Migration section should be at the end (most of the time is irrelevant).
2. How to test should be before related PRs, again we will have to write a how to test most of the time and having related PRs won't happen that much.
3. TODO should be after how to test and before related PRs.
4. We could add the word _Thanks_ at the end :rofl:.

Let me know your thoughts, mentioning @tatianacmh because she is the creator of the template.

Thanks.

**Comment by rkmax** [comment]
@jac1013 what do you think about to get rid the N/A sections to avoid noise

**Comment by jac1013** [comment]
@rkmax yeah, instead of putting N/A we should just remove that section if it doesn't apply, I agree with you.

**Comment by tatianacmh** [comment]
I agree with you guys @jac1013 , @rkmax , after you take a look at #5  and approve it, I will update the wiki doc, Thanks!

**Comment by ghost** [comment]
Agree with @jac1013 and @rkmax .

Also, we should also include the keywords to use when a Pull Request closes an issue as shown here https://help.github.com/articles/closing-issues-via-commit-messages/

What do you guys think?

**Comment by tatianacmh** [comment]
@evasquez26 , but that is when we merge the pr, right? So I don't think is related to the template itself.
Although I can mention that in the wiki as a pro tip.

**Comment by jac1013** [comment]
Hey Guys, I love the idea of using special keywords in commit messages, still I agree with @tatianacmh that is not related to this issue or pull request template itself, maybe it could be mention somewhere in the documentation of pull requests but I don't think is a good idea to put it in the template.
